{ File Generated on 2004-08-14 automatically }
{ and encoded in the ISO-8859-1 character set}
const
  MAX_CASETABLE_ENTRIES =766;
type
  TCaseFoldingInfo = record
    lower: ucs4char;
    upper: ucs4char;
  end;


const
  UCS4CaseTable: array[1..MAX_CASETABLE_ENTRIES] of TCaseFoldingInfo = (
  (
   lower: $0061;
   upper: $0041
  ),
  (
   lower: $0062;
   upper: $0042
  ),
  (
   lower: $0063;
   upper: $0043
  ),
  (
   lower: $0064;
   upper: $0044
  ),
  (
   lower: $0065;
   upper: $0045
  ),
  (
   lower: $0066;
   upper: $0046
  ),
  (
   lower: $0067;
   upper: $0047
  ),
  (
   lower: $0068;
   upper: $0048
  ),
  (
   lower: $0069;
   upper: $0049
  ),
  (
   lower: $006A;
   upper: $004A
  ),
  (
   lower: $006B;
   upper: $004B
  ),
  (
   lower: $006C;
   upper: $004C
  ),
  (
   lower: $006D;
   upper: $004D
  ),
  (
   lower: $006E;
   upper: $004E
  ),
  (
   lower: $006F;
   upper: $004F
  ),
  (
   lower: $0070;
   upper: $0050
  ),
  (
   lower: $0071;
   upper: $0051
  ),
  (
   lower: $0072;
   upper: $0052
  ),
  (
   lower: $0073;
   upper: $0053
  ),
  (
   lower: $0074;
   upper: $0054
  ),
  (
   lower: $0075;
   upper: $0055
  ),
  (
   lower: $0076;
   upper: $0056
  ),
  (
   lower: $0077;
   upper: $0057
  ),
  (
   lower: $0078;
   upper: $0058
  ),
  (
   lower: $0079;
   upper: $0059
  ),
  (
   lower: $007A;
   upper: $005A
  ),
  (
   lower: $03BC;
   upper: $00B5
  ),
  (
   lower: $00E0;
   upper: $00C0
  ),
  (
   lower: $00E1;
   upper: $00C1
  ),
  (
   lower: $00E2;
   upper: $00C2
  ),
  (
   lower: $00E3;
   upper: $00C3
  ),
  (
   lower: $00E4;
   upper: $00C4
  ),
  (
   lower: $00E5;
   upper: $00C5
  ),
  (
   lower: $00E6;
   upper: $00C6
  ),
  (
   lower: $00E7;
   upper: $00C7
  ),
  (
   lower: $00E8;
   upper: $00C8
  ),
  (
   lower: $00E9;
   upper: $00C9
  ),
  (
   lower: $00EA;
   upper: $00CA
  ),
  (
   lower: $00EB;
   upper: $00CB
  ),
  (
   lower: $00EC;
   upper: $00CC
  ),
  (
   lower: $00ED;
   upper: $00CD
  ),
  (
   lower: $00EE;
   upper: $00CE
  ),
  (
   lower: $00EF;
   upper: $00CF
  ),
  (
   lower: $00F0;
   upper: $00D0
  ),
  (
   lower: $00F1;
   upper: $00D1
  ),
  (
   lower: $00F2;
   upper: $00D2
  ),
  (
   lower: $00F3;
   upper: $00D3
  ),
  (
   lower: $00F4;
   upper: $00D4
  ),
  (
   lower: $00F5;
   upper: $00D5
  ),
  (
   lower: $00F6;
   upper: $00D6
  ),
  (
   lower: $00F8;
   upper: $00D8
  ),
  (
   lower: $00F9;
   upper: $00D9
  ),
  (
   lower: $00FA;
   upper: $00DA
  ),
  (
   lower: $00FB;
   upper: $00DB
  ),
  (
   lower: $00FC;
   upper: $00DC
  ),
  (
   lower: $00FD;
   upper: $00DD
  ),
  (
   lower: $00FE;
   upper: $00DE
  ),
  (
   lower: $0101;
   upper: $0100
  ),
  (
   lower: $0103;
   upper: $0102
  ),
  (
   lower: $0105;
   upper: $0104
  ),
  (
   lower: $0107;
   upper: $0106
  ),
  (
   lower: $0109;
   upper: $0108
  ),
  (
   lower: $010B;
   upper: $010A
  ),
  (
   lower: $010D;
   upper: $010C
  ),
  (
   lower: $010F;
   upper: $010E
  ),
  (
   lower: $0111;
   upper: $0110
  ),
  (
   lower: $0113;
   upper: $0112
  ),
  (
   lower: $0115;
   upper: $0114
  ),
  (
   lower: $0117;
   upper: $0116
  ),
  (
   lower: $0119;
   upper: $0118
  ),
  (
   lower: $011B;
   upper: $011A
  ),
  (
   lower: $011D;
   upper: $011C
  ),
  (
   lower: $011F;
   upper: $011E
  ),
  (
   lower: $0121;
   upper: $0120
  ),
  (
   lower: $0123;
   upper: $0122
  ),
  (
   lower: $0125;
   upper: $0124
  ),
  (
   lower: $0127;
   upper: $0126
  ),
  (
   lower: $0129;
   upper: $0128
  ),
  (
   lower: $012B;
   upper: $012A
  ),
  (
   lower: $012D;
   upper: $012C
  ),
  (
   lower: $012F;
   upper: $012E
  ),
  (
   lower: $0133;
   upper: $0132
  ),
  (
   lower: $0135;
   upper: $0134
  ),
  (
   lower: $0137;
   upper: $0136
  ),
  (
   lower: $013A;
   upper: $0139
  ),
  (
   lower: $013C;
   upper: $013B
  ),
  (
   lower: $013E;
   upper: $013D
  ),
  (
   lower: $0140;
   upper: $013F
  ),
  (
   lower: $0142;
   upper: $0141
  ),
  (
   lower: $0144;
   upper: $0143
  ),
  (
   lower: $0146;
   upper: $0145
  ),
  (
   lower: $0148;
   upper: $0147
  ),
  (
   lower: $014B;
   upper: $014A
  ),
  (
   lower: $014D;
   upper: $014C
  ),
  (
   lower: $014F;
   upper: $014E
  ),
  (
   lower: $0151;
   upper: $0150
  ),
  (
   lower: $0153;
   upper: $0152
  ),
  (
   lower: $0155;
   upper: $0154
  ),
  (
   lower: $0157;
   upper: $0156
  ),
  (
   lower: $0159;
   upper: $0158
  ),
  (
   lower: $015B;
   upper: $015A
  ),
  (
   lower: $015D;
   upper: $015C
  ),
  (
   lower: $015F;
   upper: $015E
  ),
  (
   lower: $0161;
   upper: $0160
  ),
  (
   lower: $0163;
   upper: $0162
  ),
  (
   lower: $0165;
   upper: $0164
  ),
  (
   lower: $0167;
   upper: $0166
  ),
  (
   lower: $0169;
   upper: $0168
  ),
  (
   lower: $016B;
   upper: $016A
  ),
  (
   lower: $016D;
   upper: $016C
  ),
  (
   lower: $016F;
   upper: $016E
  ),
  (
   lower: $0171;
   upper: $0170
  ),
  (
   lower: $0173;
   upper: $0172
  ),
  (
   lower: $0175;
   upper: $0174
  ),
  (
   lower: $0177;
   upper: $0176
  ),
  (
   lower: $00FF;
   upper: $0178
  ),
  (
   lower: $017A;
   upper: $0179
  ),
  (
   lower: $017C;
   upper: $017B
  ),
  (
   lower: $017E;
   upper: $017D
  ),
  (
   lower: $0073;
   upper: $017F
  ),
  (
   lower: $0253;
   upper: $0181
  ),
  (
   lower: $0183;
   upper: $0182
  ),
  (
   lower: $0185;
   upper: $0184
  ),
  (
   lower: $0254;
   upper: $0186
  ),
  (
   lower: $0188;
   upper: $0187
  ),
  (
   lower: $0256;
   upper: $0189
  ),
  (
   lower: $0257;
   upper: $018A
  ),
  (
   lower: $018C;
   upper: $018B
  ),
  (
   lower: $01DD;
   upper: $018E
  ),
  (
   lower: $0259;
   upper: $018F
  ),
  (
   lower: $025B;
   upper: $0190
  ),
  (
   lower: $0192;
   upper: $0191
  ),
  (
   lower: $0260;
   upper: $0193
  ),
  (
   lower: $0263;
   upper: $0194
  ),
  (
   lower: $0269;
   upper: $0196
  ),
  (
   lower: $0268;
   upper: $0197
  ),
  (
   lower: $0199;
   upper: $0198
  ),
  (
   lower: $026F;
   upper: $019C
  ),
  (
   lower: $0272;
   upper: $019D
  ),
  (
   lower: $0275;
   upper: $019F
  ),
  (
   lower: $01A1;
   upper: $01A0
  ),
  (
   lower: $01A3;
   upper: $01A2
  ),
  (
   lower: $01A5;
   upper: $01A4
  ),
  (
   lower: $0280;
   upper: $01A6
  ),
  (
   lower: $01A8;
   upper: $01A7
  ),
  (
   lower: $0283;
   upper: $01A9
  ),
  (
   lower: $01AD;
   upper: $01AC
  ),
  (
   lower: $0288;
   upper: $01AE
  ),
  (
   lower: $01B0;
   upper: $01AF
  ),
  (
   lower: $028A;
   upper: $01B1
  ),
  (
   lower: $028B;
   upper: $01B2
  ),
  (
   lower: $01B4;
   upper: $01B3
  ),
  (
   lower: $01B6;
   upper: $01B5
  ),
  (
   lower: $0292;
   upper: $01B7
  ),
  (
   lower: $01B9;
   upper: $01B8
  ),
  (
   lower: $01BD;
   upper: $01BC
  ),
  (
   lower: $01C6;
   upper: $01C4
  ),
  (
   lower: $01C6;
   upper: $01C5
  ),
  (
   lower: $01C9;
   upper: $01C7
  ),
  (
   lower: $01C9;
   upper: $01C8
  ),
  (
   lower: $01CC;
   upper: $01CA
  ),
  (
   lower: $01CC;
   upper: $01CB
  ),
  (
   lower: $01CE;
   upper: $01CD
  ),
  (
   lower: $01D0;
   upper: $01CF
  ),
  (
   lower: $01D2;
   upper: $01D1
  ),
  (
   lower: $01D4;
   upper: $01D3
  ),
  (
   lower: $01D6;
   upper: $01D5
  ),
  (
   lower: $01D8;
   upper: $01D7
  ),
  (
   lower: $01DA;
   upper: $01D9
  ),
  (
   lower: $01DC;
   upper: $01DB
  ),
  (
   lower: $01DF;
   upper: $01DE
  ),
  (
   lower: $01E1;
   upper: $01E0
  ),
  (
   lower: $01E3;
   upper: $01E2
  ),
  (
   lower: $01E5;
   upper: $01E4
  ),
  (
   lower: $01E7;
   upper: $01E6
  ),
  (
   lower: $01E9;
   upper: $01E8
  ),
  (
   lower: $01EB;
   upper: $01EA
  ),
  (
   lower: $01ED;
   upper: $01EC
  ),
  (
   lower: $01EF;
   upper: $01EE
  ),
  (
   lower: $01F3;
   upper: $01F1
  ),
  (
   lower: $01F3;
   upper: $01F2
  ),
  (
   lower: $01F5;
   upper: $01F4
  ),
  (
   lower: $0195;
   upper: $01F6
  ),
  (
   lower: $01BF;
   upper: $01F7
  ),
  (
   lower: $01F9;
   upper: $01F8
  ),
  (
   lower: $01FB;
   upper: $01FA
  ),
  (
   lower: $01FD;
   upper: $01FC
  ),
  (
   lower: $01FF;
   upper: $01FE
  ),
  (
   lower: $0201;
   upper: $0200
  ),
  (
   lower: $0203;
   upper: $0202
  ),
  (
   lower: $0205;
   upper: $0204
  ),
  (
   lower: $0207;
   upper: $0206
  ),
  (
   lower: $0209;
   upper: $0208
  ),
  (
   lower: $020B;
   upper: $020A
  ),
  (
   lower: $020D;
   upper: $020C
  ),
  (
   lower: $020F;
   upper: $020E
  ),
  (
   lower: $0211;
   upper: $0210
  ),
  (
   lower: $0213;
   upper: $0212
  ),
  (
   lower: $0215;
   upper: $0214
  ),
  (
   lower: $0217;
   upper: $0216
  ),
  (
   lower: $0219;
   upper: $0218
  ),
  (
   lower: $021B;
   upper: $021A
  ),
  (
   lower: $021D;
   upper: $021C
  ),
  (
   lower: $021F;
   upper: $021E
  ),
  (
   lower: $019E;
   upper: $0220
  ),
  (
   lower: $0223;
   upper: $0222
  ),
  (
   lower: $0225;
   upper: $0224
  ),
  (
   lower: $0227;
   upper: $0226
  ),
  (
   lower: $0229;
   upper: $0228
  ),
  (
   lower: $022B;
   upper: $022A
  ),
  (
   lower: $022D;
   upper: $022C
  ),
  (
   lower: $022F;
   upper: $022E
  ),
  (
   lower: $0231;
   upper: $0230
  ),
  (
   lower: $0233;
   upper: $0232
  ),
  (
   lower: $03B9;
   upper: $0345
  ),
  (
   lower: $03AC;
   upper: $0386
  ),
  (
   lower: $03AD;
   upper: $0388
  ),
  (
   lower: $03AE;
   upper: $0389
  ),
  (
   lower: $03AF;
   upper: $038A
  ),
  (
   lower: $03CC;
   upper: $038C
  ),
  (
   lower: $03CD;
   upper: $038E
  ),
  (
   lower: $03CE;
   upper: $038F
  ),
  (
   lower: $03B1;
   upper: $0391
  ),
  (
   lower: $03B2;
   upper: $0392
  ),
  (
   lower: $03B3;
   upper: $0393
  ),
  (
   lower: $03B4;
   upper: $0394
  ),
  (
   lower: $03B5;
   upper: $0395
  ),
  (
   lower: $03B6;
   upper: $0396
  ),
  (
   lower: $03B7;
   upper: $0397
  ),
  (
   lower: $03B8;
   upper: $0398
  ),
  (
   lower: $03B9;
   upper: $0399
  ),
  (
   lower: $03BA;
   upper: $039A
  ),
  (
   lower: $03BB;
   upper: $039B
  ),
  (
   lower: $03BC;
   upper: $039C
  ),
  (
   lower: $03BD;
   upper: $039D
  ),
  (
   lower: $03BE;
   upper: $039E
  ),
  (
   lower: $03BF;
   upper: $039F
  ),
  (
   lower: $03C0;
   upper: $03A0
  ),
  (
   lower: $03C1;
   upper: $03A1
  ),
  (
   lower: $03C3;
   upper: $03A3
  ),
  (
   lower: $03C4;
   upper: $03A4
  ),
  (
   lower: $03C5;
   upper: $03A5
  ),
  (
   lower: $03C6;
   upper: $03A6
  ),
  (
   lower: $03C7;
   upper: $03A7
  ),
  (
   lower: $03C8;
   upper: $03A8
  ),
  (
   lower: $03C9;
   upper: $03A9
  ),
  (
   lower: $03CA;
   upper: $03AA
  ),
  (
   lower: $03CB;
   upper: $03AB
  ),
  (
   lower: $03C3;
   upper: $03C2
  ),
  (
   lower: $03B2;
   upper: $03D0
  ),
  (
   lower: $03B8;
   upper: $03D1
  ),
  (
   lower: $03C6;
   upper: $03D5
  ),
  (
   lower: $03C0;
   upper: $03D6
  ),
  (
   lower: $03D9;
   upper: $03D8
  ),
  (
   lower: $03DB;
   upper: $03DA
  ),
  (
   lower: $03DD;
   upper: $03DC
  ),
  (
   lower: $03DF;
   upper: $03DE
  ),
  (
   lower: $03E1;
   upper: $03E0
  ),
  (
   lower: $03E3;
   upper: $03E2
  ),
  (
   lower: $03E5;
   upper: $03E4
  ),
  (
   lower: $03E7;
   upper: $03E6
  ),
  (
   lower: $03E9;
   upper: $03E8
  ),
  (
   lower: $03EB;
   upper: $03EA
  ),
  (
   lower: $03ED;
   upper: $03EC
  ),
  (
   lower: $03EF;
   upper: $03EE
  ),
  (
   lower: $03BA;
   upper: $03F0
  ),
  (
   lower: $03C1;
   upper: $03F1
  ),
  (
   lower: $03B8;
   upper: $03F4
  ),
  (
   lower: $03B5;
   upper: $03F5
  ),
  (
   lower: $03F8;
   upper: $03F7
  ),
  (
   lower: $03F2;
   upper: $03F9
  ),
  (
   lower: $03FB;
   upper: $03FA
  ),
  (
   lower: $0450;
   upper: $0400
  ),
  (
   lower: $0451;
   upper: $0401
  ),
  (
   lower: $0452;
   upper: $0402
  ),
  (
   lower: $0453;
   upper: $0403
  ),
  (
   lower: $0454;
   upper: $0404
  ),
  (
   lower: $0455;
   upper: $0405
  ),
  (
   lower: $0456;
   upper: $0406
  ),
  (
   lower: $0457;
   upper: $0407
  ),
  (
   lower: $0458;
   upper: $0408
  ),
  (
   lower: $0459;
   upper: $0409
  ),
  (
   lower: $045A;
   upper: $040A
  ),
  (
   lower: $045B;
   upper: $040B
  ),
  (
   lower: $045C;
   upper: $040C
  ),
  (
   lower: $045D;
   upper: $040D
  ),
  (
   lower: $045E;
   upper: $040E
  ),
  (
   lower: $045F;
   upper: $040F
  ),
  (
   lower: $0430;
   upper: $0410
  ),
  (
   lower: $0431;
   upper: $0411
  ),
  (
   lower: $0432;
   upper: $0412
  ),
  (
   lower: $0433;
   upper: $0413
  ),
  (
   lower: $0434;
   upper: $0414
  ),
  (
   lower: $0435;
   upper: $0415
  ),
  (
   lower: $0436;
   upper: $0416
  ),
  (
   lower: $0437;
   upper: $0417
  ),
  (
   lower: $0438;
   upper: $0418
  ),
  (
   lower: $0439;
   upper: $0419
  ),
  (
   lower: $043A;
   upper: $041A
  ),
  (
   lower: $043B;
   upper: $041B
  ),
  (
   lower: $043C;
   upper: $041C
  ),
  (
   lower: $043D;
   upper: $041D
  ),
  (
   lower: $043E;
   upper: $041E
  ),
  (
   lower: $043F;
   upper: $041F
  ),
  (
   lower: $0440;
   upper: $0420
  ),
  (
   lower: $0441;
   upper: $0421
  ),
  (
   lower: $0442;
   upper: $0422
  ),
  (
   lower: $0443;
   upper: $0423
  ),
  (
   lower: $0444;
   upper: $0424
  ),
  (
   lower: $0445;
   upper: $0425
  ),
  (
   lower: $0446;
   upper: $0426
  ),
  (
   lower: $0447;
   upper: $0427
  ),
  (
   lower: $0448;
   upper: $0428
  ),
  (
   lower: $0449;
   upper: $0429
  ),
  (
   lower: $044A;
   upper: $042A
  ),
  (
   lower: $044B;
   upper: $042B
  ),
  (
   lower: $044C;
   upper: $042C
  ),
  (
   lower: $044D;
   upper: $042D
  ),
  (
   lower: $044E;
   upper: $042E
  ),
  (
   lower: $044F;
   upper: $042F
  ),
  (
   lower: $0461;
   upper: $0460
  ),
  (
   lower: $0463;
   upper: $0462
  ),
  (
   lower: $0465;
   upper: $0464
  ),
  (
   lower: $0467;
   upper: $0466
  ),
  (
   lower: $0469;
   upper: $0468
  ),
  (
   lower: $046B;
   upper: $046A
  ),
  (
   lower: $046D;
   upper: $046C
  ),
  (
   lower: $046F;
   upper: $046E
  ),
  (
   lower: $0471;
   upper: $0470
  ),
  (
   lower: $0473;
   upper: $0472
  ),
  (
   lower: $0475;
   upper: $0474
  ),
  (
   lower: $0477;
   upper: $0476
  ),
  (
   lower: $0479;
   upper: $0478
  ),
  (
   lower: $047B;
   upper: $047A
  ),
  (
   lower: $047D;
   upper: $047C
  ),
  (
   lower: $047F;
   upper: $047E
  ),
  (
   lower: $0481;
   upper: $0480
  ),
  (
   lower: $048B;
   upper: $048A
  ),
  (
   lower: $048D;
   upper: $048C
  ),
  (
   lower: $048F;
   upper: $048E
  ),
  (
   lower: $0491;
   upper: $0490
  ),
  (
   lower: $0493;
   upper: $0492
  ),
  (
   lower: $0495;
   upper: $0494
  ),
  (
   lower: $0497;
   upper: $0496
  ),
  (
   lower: $0499;
   upper: $0498
  ),
  (
   lower: $049B;
   upper: $049A
  ),
  (
   lower: $049D;
   upper: $049C
  ),
  (
   lower: $049F;
   upper: $049E
  ),
  (
   lower: $04A1;
   upper: $04A0
  ),
  (
   lower: $04A3;
   upper: $04A2
  ),
  (
   lower: $04A5;
   upper: $04A4
  ),
  (
   lower: $04A7;
   upper: $04A6
  ),
  (
   lower: $04A9;
   upper: $04A8
  ),
  (
   lower: $04AB;
   upper: $04AA
  ),
  (
   lower: $04AD;
   upper: $04AC
  ),
  (
   lower: $04AF;
   upper: $04AE
  ),
  (
   lower: $04B1;
   upper: $04B0
  ),
  (
   lower: $04B3;
   upper: $04B2
  ),
  (
   lower: $04B5;
   upper: $04B4
  ),
  (
   lower: $04B7;
   upper: $04B6
  ),
  (
   lower: $04B9;
   upper: $04B8
  ),
  (
   lower: $04BB;
   upper: $04BA
  ),
  (
   lower: $04BD;
   upper: $04BC
  ),
  (
   lower: $04BF;
   upper: $04BE
  ),
  (
   lower: $04C2;
   upper: $04C1
  ),
  (
   lower: $04C4;
   upper: $04C3
  ),
  (
   lower: $04C6;
   upper: $04C5
  ),
  (
   lower: $04C8;
   upper: $04C7
  ),
  (
   lower: $04CA;
   upper: $04C9
  ),
  (
   lower: $04CC;
   upper: $04CB
  ),
  (
   lower: $04CE;
   upper: $04CD
  ),
  (
   lower: $04D1;
   upper: $04D0
  ),
  (
   lower: $04D3;
   upper: $04D2
  ),
  (
   lower: $04D5;
   upper: $04D4
  ),
  (
   lower: $04D7;
   upper: $04D6
  ),
  (
   lower: $04D9;
   upper: $04D8
  ),
  (
   lower: $04DB;
   upper: $04DA
  ),
  (
   lower: $04DD;
   upper: $04DC
  ),
  (
   lower: $04DF;
   upper: $04DE
  ),
  (
   lower: $04E1;
   upper: $04E0
  ),
  (
   lower: $04E3;
   upper: $04E2
  ),
  (
   lower: $04E5;
   upper: $04E4
  ),
  (
   lower: $04E7;
   upper: $04E6
  ),
  (
   lower: $04E9;
   upper: $04E8
  ),
  (
   lower: $04EB;
   upper: $04EA
  ),
  (
   lower: $04ED;
   upper: $04EC
  ),
  (
   lower: $04EF;
   upper: $04EE
  ),
  (
   lower: $04F1;
   upper: $04F0
  ),
  (
   lower: $04F3;
   upper: $04F2
  ),
  (
   lower: $04F5;
   upper: $04F4
  ),
  (
   lower: $04F9;
   upper: $04F8
  ),
  (
   lower: $0501;
   upper: $0500
  ),
  (
   lower: $0503;
   upper: $0502
  ),
  (
   lower: $0505;
   upper: $0504
  ),
  (
   lower: $0507;
   upper: $0506
  ),
  (
   lower: $0509;
   upper: $0508
  ),
  (
   lower: $050B;
   upper: $050A
  ),
  (
   lower: $050D;
   upper: $050C
  ),
  (
   lower: $050F;
   upper: $050E
  ),
  (
   lower: $0561;
   upper: $0531
  ),
  (
   lower: $0562;
   upper: $0532
  ),
  (
   lower: $0563;
   upper: $0533
  ),
  (
   lower: $0564;
   upper: $0534
  ),
  (
   lower: $0565;
   upper: $0535
  ),
  (
   lower: $0566;
   upper: $0536
  ),
  (
   lower: $0567;
   upper: $0537
  ),
  (
   lower: $0568;
   upper: $0538
  ),
  (
   lower: $0569;
   upper: $0539
  ),
  (
   lower: $056A;
   upper: $053A
  ),
  (
   lower: $056B;
   upper: $053B
  ),
  (
   lower: $056C;
   upper: $053C
  ),
  (
   lower: $056D;
   upper: $053D
  ),
  (
   lower: $056E;
   upper: $053E
  ),
  (
   lower: $056F;
   upper: $053F
  ),
  (
   lower: $0570;
   upper: $0540
  ),
  (
   lower: $0571;
   upper: $0541
  ),
  (
   lower: $0572;
   upper: $0542
  ),
  (
   lower: $0573;
   upper: $0543
  ),
  (
   lower: $0574;
   upper: $0544
  ),
  (
   lower: $0575;
   upper: $0545
  ),
  (
   lower: $0576;
   upper: $0546
  ),
  (
   lower: $0577;
   upper: $0547
  ),
  (
   lower: $0578;
   upper: $0548
  ),
  (
   lower: $0579;
   upper: $0549
  ),
  (
   lower: $057A;
   upper: $054A
  ),
  (
   lower: $057B;
   upper: $054B
  ),
  (
   lower: $057C;
   upper: $054C
  ),
  (
   lower: $057D;
   upper: $054D
  ),
  (
   lower: $057E;
   upper: $054E
  ),
  (
   lower: $057F;
   upper: $054F
  ),
  (
   lower: $0580;
   upper: $0550
  ),
  (
   lower: $0581;
   upper: $0551
  ),
  (
   lower: $0582;
   upper: $0552
  ),
  (
   lower: $0583;
   upper: $0553
  ),
  (
   lower: $0584;
   upper: $0554
  ),
  (
   lower: $0585;
   upper: $0555
  ),
  (
   lower: $0586;
   upper: $0556
  ),
  (
   lower: $1E01;
   upper: $1E00
  ),
  (
   lower: $1E03;
   upper: $1E02
  ),
  (
   lower: $1E05;
   upper: $1E04
  ),
  (
   lower: $1E07;
   upper: $1E06
  ),
  (
   lower: $1E09;
   upper: $1E08
  ),
  (
   lower: $1E0B;
   upper: $1E0A
  ),
  (
   lower: $1E0D;
   upper: $1E0C
  ),
  (
   lower: $1E0F;
   upper: $1E0E
  ),
  (
   lower: $1E11;
   upper: $1E10
  ),
  (
   lower: $1E13;
   upper: $1E12
  ),
  (
   lower: $1E15;
   upper: $1E14
  ),
  (
   lower: $1E17;
   upper: $1E16
  ),
  (
   lower: $1E19;
   upper: $1E18
  ),
  (
   lower: $1E1B;
   upper: $1E1A
  ),
  (
   lower: $1E1D;
   upper: $1E1C
  ),
  (
   lower: $1E1F;
   upper: $1E1E
  ),
  (
   lower: $1E21;
   upper: $1E20
  ),
  (
   lower: $1E23;
   upper: $1E22
  ),
  (
   lower: $1E25;
   upper: $1E24
  ),
  (
   lower: $1E27;
   upper: $1E26
  ),
  (
   lower: $1E29;
   upper: $1E28
  ),
  (
   lower: $1E2B;
   upper: $1E2A
  ),
  (
   lower: $1E2D;
   upper: $1E2C
  ),
  (
   lower: $1E2F;
   upper: $1E2E
  ),
  (
   lower: $1E31;
   upper: $1E30
  ),
  (
   lower: $1E33;
   upper: $1E32
  ),
  (
   lower: $1E35;
   upper: $1E34
  ),
  (
   lower: $1E37;
   upper: $1E36
  ),
  (
   lower: $1E39;
   upper: $1E38
  ),
  (
   lower: $1E3B;
   upper: $1E3A
  ),
  (
   lower: $1E3D;
   upper: $1E3C
  ),
  (
   lower: $1E3F;
   upper: $1E3E
  ),
  (
   lower: $1E41;
   upper: $1E40
  ),
  (
   lower: $1E43;
   upper: $1E42
  ),
  (
   lower: $1E45;
   upper: $1E44
  ),
  (
   lower: $1E47;
   upper: $1E46
  ),
  (
   lower: $1E49;
   upper: $1E48
  ),
  (
   lower: $1E4B;
   upper: $1E4A
  ),
  (
   lower: $1E4D;
   upper: $1E4C
  ),
  (
   lower: $1E4F;
   upper: $1E4E
  ),
  (
   lower: $1E51;
   upper: $1E50
  ),
  (
   lower: $1E53;
   upper: $1E52
  ),
  (
   lower: $1E55;
   upper: $1E54
  ),
  (
   lower: $1E57;
   upper: $1E56
  ),
  (
   lower: $1E59;
   upper: $1E58
  ),
  (
   lower: $1E5B;
   upper: $1E5A
  ),
  (
   lower: $1E5D;
   upper: $1E5C
  ),
  (
   lower: $1E5F;
   upper: $1E5E
  ),
  (
   lower: $1E61;
   upper: $1E60
  ),
  (
   lower: $1E63;
   upper: $1E62
  ),
  (
   lower: $1E65;
   upper: $1E64
  ),
  (
   lower: $1E67;
   upper: $1E66
  ),
  (
   lower: $1E69;
   upper: $1E68
  ),
  (
   lower: $1E6B;
   upper: $1E6A
  ),
  (
   lower: $1E6D;
   upper: $1E6C
  ),
  (
   lower: $1E6F;
   upper: $1E6E
  ),
  (
   lower: $1E71;
   upper: $1E70
  ),
  (
   lower: $1E73;
   upper: $1E72
  ),
  (
   lower: $1E75;
   upper: $1E74
  ),
  (
   lower: $1E77;
   upper: $1E76
  ),
  (
   lower: $1E79;
   upper: $1E78
  ),
  (
   lower: $1E7B;
   upper: $1E7A
  ),
  (
   lower: $1E7D;
   upper: $1E7C
  ),
  (
   lower: $1E7F;
   upper: $1E7E
  ),
  (
   lower: $1E81;
   upper: $1E80
  ),
  (
   lower: $1E83;
   upper: $1E82
  ),
  (
   lower: $1E85;
   upper: $1E84
  ),
  (
   lower: $1E87;
   upper: $1E86
  ),
  (
   lower: $1E89;
   upper: $1E88
  ),
  (
   lower: $1E8B;
   upper: $1E8A
  ),
  (
   lower: $1E8D;
   upper: $1E8C
  ),
  (
   lower: $1E8F;
   upper: $1E8E
  ),
  (
   lower: $1E91;
   upper: $1E90
  ),
  (
   lower: $1E93;
   upper: $1E92
  ),
  (
   lower: $1E95;
   upper: $1E94
  ),
  (
   lower: $1E61;
   upper: $1E9B
  ),
  (
   lower: $1EA1;
   upper: $1EA0
  ),
  (
   lower: $1EA3;
   upper: $1EA2
  ),
  (
   lower: $1EA5;
   upper: $1EA4
  ),
  (
   lower: $1EA7;
   upper: $1EA6
  ),
  (
   lower: $1EA9;
   upper: $1EA8
  ),
  (
   lower: $1EAB;
   upper: $1EAA
  ),
  (
   lower: $1EAD;
   upper: $1EAC
  ),
  (
   lower: $1EAF;
   upper: $1EAE
  ),
  (
   lower: $1EB1;
   upper: $1EB0
  ),
  (
   lower: $1EB3;
   upper: $1EB2
  ),
  (
   lower: $1EB5;
   upper: $1EB4
  ),
  (
   lower: $1EB7;
   upper: $1EB6
  ),
  (
   lower: $1EB9;
   upper: $1EB8
  ),
  (
   lower: $1EBB;
   upper: $1EBA
  ),
  (
   lower: $1EBD;
   upper: $1EBC
  ),
  (
   lower: $1EBF;
   upper: $1EBE
  ),
  (
   lower: $1EC1;
   upper: $1EC0
  ),
  (
   lower: $1EC3;
   upper: $1EC2
  ),
  (
   lower: $1EC5;
   upper: $1EC4
  ),
  (
   lower: $1EC7;
   upper: $1EC6
  ),
  (
   lower: $1EC9;
   upper: $1EC8
  ),
  (
   lower: $1ECB;
   upper: $1ECA
  ),
  (
   lower: $1ECD;
   upper: $1ECC
  ),
  (
   lower: $1ECF;
   upper: $1ECE
  ),
  (
   lower: $1ED1;
   upper: $1ED0
  ),
  (
   lower: $1ED3;
   upper: $1ED2
  ),
  (
   lower: $1ED5;
   upper: $1ED4
  ),
  (
   lower: $1ED7;
   upper: $1ED6
  ),
  (
   lower: $1ED9;
   upper: $1ED8
  ),
  (
   lower: $1EDB;
   upper: $1EDA
  ),
  (
   lower: $1EDD;
   upper: $1EDC
  ),
  (
   lower: $1EDF;
   upper: $1EDE
  ),
  (
   lower: $1EE1;
   upper: $1EE0
  ),
  (
   lower: $1EE3;
   upper: $1EE2
  ),
  (
   lower: $1EE5;
   upper: $1EE4
  ),
  (
   lower: $1EE7;
   upper: $1EE6
  ),
  (
   lower: $1EE9;
   upper: $1EE8
  ),
  (
   lower: $1EEB;
   upper: $1EEA
  ),
  (
   lower: $1EED;
   upper: $1EEC
  ),
  (
   lower: $1EEF;
   upper: $1EEE
  ),
  (
   lower: $1EF1;
   upper: $1EF0
  ),
  (
   lower: $1EF3;
   upper: $1EF2
  ),
  (
   lower: $1EF5;
   upper: $1EF4
  ),
  (
   lower: $1EF7;
   upper: $1EF6
  ),
  (
   lower: $1EF9;
   upper: $1EF8
  ),
  (
   lower: $1F00;
   upper: $1F08
  ),
  (
   lower: $1F01;
   upper: $1F09
  ),
  (
   lower: $1F02;
   upper: $1F0A
  ),
  (
   lower: $1F03;
   upper: $1F0B
  ),
  (
   lower: $1F04;
   upper: $1F0C
  ),
  (
   lower: $1F05;
   upper: $1F0D
  ),
  (
   lower: $1F06;
   upper: $1F0E
  ),
  (
   lower: $1F07;
   upper: $1F0F
  ),
  (
   lower: $1F10;
   upper: $1F18
  ),
  (
   lower: $1F11;
   upper: $1F19
  ),
  (
   lower: $1F12;
   upper: $1F1A
  ),
  (
   lower: $1F13;
   upper: $1F1B
  ),
  (
   lower: $1F14;
   upper: $1F1C
  ),
  (
   lower: $1F15;
   upper: $1F1D
  ),
  (
   lower: $1F20;
   upper: $1F28
  ),
  (
   lower: $1F21;
   upper: $1F29
  ),
  (
   lower: $1F22;
   upper: $1F2A
  ),
  (
   lower: $1F23;
   upper: $1F2B
  ),
  (
   lower: $1F24;
   upper: $1F2C
  ),
  (
   lower: $1F25;
   upper: $1F2D
  ),
  (
   lower: $1F26;
   upper: $1F2E
  ),
  (
   lower: $1F27;
   upper: $1F2F
  ),
  (
   lower: $1F30;
   upper: $1F38
  ),
  (
   lower: $1F31;
   upper: $1F39
  ),
  (
   lower: $1F32;
   upper: $1F3A
  ),
  (
   lower: $1F33;
   upper: $1F3B
  ),
  (
   lower: $1F34;
   upper: $1F3C
  ),
  (
   lower: $1F35;
   upper: $1F3D
  ),
  (
   lower: $1F36;
   upper: $1F3E
  ),
  (
   lower: $1F37;
   upper: $1F3F
  ),
  (
   lower: $1F40;
   upper: $1F48
  ),
  (
   lower: $1F41;
   upper: $1F49
  ),
  (
   lower: $1F42;
   upper: $1F4A
  ),
  (
   lower: $1F43;
   upper: $1F4B
  ),
  (
   lower: $1F44;
   upper: $1F4C
  ),
  (
   lower: $1F45;
   upper: $1F4D
  ),
  (
   lower: $1F51;
   upper: $1F59
  ),
  (
   lower: $1F53;
   upper: $1F5B
  ),
  (
   lower: $1F55;
   upper: $1F5D
  ),
  (
   lower: $1F57;
   upper: $1F5F
  ),
  (
   lower: $1F60;
   upper: $1F68
  ),
  (
   lower: $1F61;
   upper: $1F69
  ),
  (
   lower: $1F62;
   upper: $1F6A
  ),
  (
   lower: $1F63;
   upper: $1F6B
  ),
  (
   lower: $1F64;
   upper: $1F6C
  ),
  (
   lower: $1F65;
   upper: $1F6D
  ),
  (
   lower: $1F66;
   upper: $1F6E
  ),
  (
   lower: $1F67;
   upper: $1F6F
  ),
  (
   lower: $1F80;
   upper: $1F88
  ),
  (
   lower: $1F81;
   upper: $1F89
  ),
  (
   lower: $1F82;
   upper: $1F8A
  ),
  (
   lower: $1F83;
   upper: $1F8B
  ),
  (
   lower: $1F84;
   upper: $1F8C
  ),
  (
   lower: $1F85;
   upper: $1F8D
  ),
  (
   lower: $1F86;
   upper: $1F8E
  ),
  (
   lower: $1F87;
   upper: $1F8F
  ),
  (
   lower: $1F90;
   upper: $1F98
  ),
  (
   lower: $1F91;
   upper: $1F99
  ),
  (
   lower: $1F92;
   upper: $1F9A
  ),
  (
   lower: $1F93;
   upper: $1F9B
  ),
  (
   lower: $1F94;
   upper: $1F9C
  ),
  (
   lower: $1F95;
   upper: $1F9D
  ),
  (
   lower: $1F96;
   upper: $1F9E
  ),
  (
   lower: $1F97;
   upper: $1F9F
  ),
  (
   lower: $1FA0;
   upper: $1FA8
  ),
  (
   lower: $1FA1;
   upper: $1FA9
  ),
  (
   lower: $1FA2;
   upper: $1FAA
  ),
  (
   lower: $1FA3;
   upper: $1FAB
  ),
  (
   lower: $1FA4;
   upper: $1FAC
  ),
  (
   lower: $1FA5;
   upper: $1FAD
  ),
  (
   lower: $1FA6;
   upper: $1FAE
  ),
  (
   lower: $1FA7;
   upper: $1FAF
  ),
  (
   lower: $1FB0;
   upper: $1FB8
  ),
  (
   lower: $1FB1;
   upper: $1FB9
  ),
  (
   lower: $1F70;
   upper: $1FBA
  ),
  (
   lower: $1F71;
   upper: $1FBB
  ),
  (
   lower: $1FB3;
   upper: $1FBC
  ),
  (
   lower: $03B9;
   upper: $1FBE
  ),
  (
   lower: $1F72;
   upper: $1FC8
  ),
  (
   lower: $1F73;
   upper: $1FC9
  ),
  (
   lower: $1F74;
   upper: $1FCA
  ),
  (
   lower: $1F75;
   upper: $1FCB
  ),
  (
   lower: $1FC3;
   upper: $1FCC
  ),
  (
   lower: $1FD0;
   upper: $1FD8
  ),
  (
   lower: $1FD1;
   upper: $1FD9
  ),
  (
   lower: $1F76;
   upper: $1FDA
  ),
  (
   lower: $1F77;
   upper: $1FDB
  ),
  (
   lower: $1FE0;
   upper: $1FE8
  ),
  (
   lower: $1FE1;
   upper: $1FE9
  ),
  (
   lower: $1F7A;
   upper: $1FEA
  ),
  (
   lower: $1F7B;
   upper: $1FEB
  ),
  (
   lower: $1FE5;
   upper: $1FEC
  ),
  (
   lower: $1F78;
   upper: $1FF8
  ),
  (
   lower: $1F79;
   upper: $1FF9
  ),
  (
   lower: $1F7C;
   upper: $1FFA
  ),
  (
   lower: $1F7D;
   upper: $1FFB
  ),
  (
   lower: $1FF3;
   upper: $1FFC
  ),
  (
   lower: $03C9;
   upper: $2126
  ),
  (
   lower: $006B;
   upper: $212A
  ),
  (
   lower: $00E5;
   upper: $212B
  ),
  (
   lower: $2170;
   upper: $2160
  ),
  (
   lower: $2171;
   upper: $2161
  ),
  (
   lower: $2172;
   upper: $2162
  ),
  (
   lower: $2173;
   upper: $2163
  ),
  (
   lower: $2174;
   upper: $2164
  ),
  (
   lower: $2175;
   upper: $2165
  ),
  (
   lower: $2176;
   upper: $2166
  ),
  (
   lower: $2177;
   upper: $2167
  ),
  (
   lower: $2178;
   upper: $2168
  ),
  (
   lower: $2179;
   upper: $2169
  ),
  (
   lower: $217A;
   upper: $216A
  ),
  (
   lower: $217B;
   upper: $216B
  ),
  (
   lower: $217C;
   upper: $216C
  ),
  (
   lower: $217D;
   upper: $216D
  ),
  (
   lower: $217E;
   upper: $216E
  ),
  (
   lower: $217F;
   upper: $216F
  ),
  (
   lower: $24D0;
   upper: $24B6
  ),
  (
   lower: $24D1;
   upper: $24B7
  ),
  (
   lower: $24D2;
   upper: $24B8
  ),
  (
   lower: $24D3;
   upper: $24B9
  ),
  (
   lower: $24D4;
   upper: $24BA
  ),
  (
   lower: $24D5;
   upper: $24BB
  ),
  (
   lower: $24D6;
   upper: $24BC
  ),
  (
   lower: $24D7;
   upper: $24BD
  ),
  (
   lower: $24D8;
   upper: $24BE
  ),
  (
   lower: $24D9;
   upper: $24BF
  ),
  (
   lower: $24DA;
   upper: $24C0
  ),
  (
   lower: $24DB;
   upper: $24C1
  ),
  (
   lower: $24DC;
   upper: $24C2
  ),
  (
   lower: $24DD;
   upper: $24C3
  ),
  (
   lower: $24DE;
   upper: $24C4
  ),
  (
   lower: $24DF;
   upper: $24C5
  ),
  (
   lower: $24E0;
   upper: $24C6
  ),
  (
   lower: $24E1;
   upper: $24C7
  ),
  (
   lower: $24E2;
   upper: $24C8
  ),
  (
   lower: $24E3;
   upper: $24C9
  ),
  (
   lower: $24E4;
   upper: $24CA
  ),
  (
   lower: $24E5;
   upper: $24CB
  ),
  (
   lower: $24E6;
   upper: $24CC
  ),
  (
   lower: $24E7;
   upper: $24CD
  ),
  (
   lower: $24E8;
   upper: $24CE
  ),
  (
   lower: $24E9;
   upper: $24CF
  ),
  (
   lower: $FF41;
   upper: $FF21
  ),
  (
   lower: $FF42;
   upper: $FF22
  ),
  (
   lower: $FF43;
   upper: $FF23
  ),
  (
   lower: $FF44;
   upper: $FF24
  ),
  (
   lower: $FF45;
   upper: $FF25
  ),
  (
   lower: $FF46;
   upper: $FF26
  ),
  (
   lower: $FF47;
   upper: $FF27
  ),
  (
   lower: $FF48;
   upper: $FF28
  ),
  (
   lower: $FF49;
   upper: $FF29
  ),
  (
   lower: $FF4A;
   upper: $FF2A
  ),
  (
   lower: $FF4B;
   upper: $FF2B
  ),
  (
   lower: $FF4C;
   upper: $FF2C
  ),
  (
   lower: $FF4D;
   upper: $FF2D
  ),
  (
   lower: $FF4E;
   upper: $FF2E
  ),
  (
   lower: $FF4F;
   upper: $FF2F
  ),
  (
   lower: $FF50;
   upper: $FF30
  ),
  (
   lower: $FF51;
   upper: $FF31
  ),
  (
   lower: $FF52;
   upper: $FF32
  ),
  (
   lower: $FF53;
   upper: $FF33
  ),
  (
   lower: $FF54;
   upper: $FF34
  ),
  (
   lower: $FF55;
   upper: $FF35
  ),
  (
   lower: $FF56;
   upper: $FF36
  ),
  (
   lower: $FF57;
   upper: $FF37
  ),
  (
   lower: $FF58;
   upper: $FF38
  ),
  (
   lower: $FF59;
   upper: $FF39
  ),
  (
   lower: $FF5A;
   upper: $FF3A
  ),
  (
   lower: $10428;
   upper: $10400
  ),
  (
   lower: $10429;
   upper: $10401
  ),
  (
   lower: $1042A;
   upper: $10402
  ),
  (
   lower: $1042B;
   upper: $10403
  ),
  (
   lower: $1042C;
   upper: $10404
  ),
  (
   lower: $1042D;
   upper: $10405
  ),
  (
   lower: $1042E;
   upper: $10406
  ),
  (
   lower: $1042F;
   upper: $10407
  ),
  (
   lower: $10430;
   upper: $10408
  ),
  (
   lower: $10431;
   upper: $10409
  ),
  (
   lower: $10432;
   upper: $1040A
  ),
  (
   lower: $10433;
   upper: $1040B
  ),
  (
   lower: $10434;
   upper: $1040C
  ),
  (
   lower: $10435;
   upper: $1040D
  ),
  (
   lower: $10436;
   upper: $1040E
  ),
  (
   lower: $10437;
   upper: $1040F
  ),
  (
   lower: $10438;
   upper: $10410
  ),
  (
   lower: $10439;
   upper: $10411
  ),
  (
   lower: $1043A;
   upper: $10412
  ),
  (
   lower: $1043B;
   upper: $10413
  ),
  (
   lower: $1043C;
   upper: $10414
  ),
  (
   lower: $1043D;
   upper: $10415
  ),
  (
   lower: $1043E;
   upper: $10416
  ),
  (
   lower: $1043F;
   upper: $10417
  ),
  (
   lower: $10440;
   upper: $10418
  ),
  (
   lower: $10441;
   upper: $10419
  ),
  (
   lower: $10442;
   upper: $1041A
  ),
  (
   lower: $10443;
   upper: $1041B
  ),
  (
   lower: $10444;
   upper: $1041C
  ),
  (
   lower: $10445;
   upper: $1041D
  ),
  (
   lower: $10446;
   upper: $1041E
  ),
  (
   lower: $10447;
   upper: $1041F
  ),
  (
   lower: $10448;
   upper: $10420
  ),
  (
   lower: $10449;
   upper: $10421
  ),
  (
   lower: $1044A;
   upper: $10422
  ),
  (
   lower: $1044B;
   upper: $10423
  ),
  (
   lower: $1044C;
   upper: $10424
  ),
  (
   lower: $1044D;
   upper: $10425
  ),
  (
   lower: $1044E;
   upper: $10426
  ),
  (
   lower: $1044F;
   upper: $10427
  )
);
